"""
Reproduce the expired-option suffix finding against LSEG.

The assignment states that the `^{M}{YY}` suffix repeats the body's month
letter. This asks LSEG for the SAME put contract under both readings and
prints how many observations each identifier returns.

    python scripts/probe_ric_suffix.py            # UUUU, the pairs in the JSON
    python scripts/probe_ric_suffix.py --write    # refresh data/ric_probe.json

Requires LSEG Workspace running. Writes nothing unless --write is passed.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from trading_app.lib.ric import CODE_TO_CP, MONTH_TO_CODE  # noqa: E402

OUT = ROOT / "trading_app" / "data" / "ric_probe.json"
PAIRS = [
    (dt.date(2026, 7, 17), 12.0), (dt.date(2026, 7, 17), 14.0),
    (dt.date(2026, 7, 31), 13.0), (dt.date(2026, 8, 21), 11.0),
    (dt.date(2026, 8, 21), 13.0), (dt.date(2026, 6, 26), 12.0),
]


def put_rics(root: str, expiry: dt.date, strike: float) -> tuple[str, str]:
    """The documented identifier and the one that actually resolves."""
    body_code = MONTH_TO_CODE["P"][expiry.month]     # T for an August put
    call_code = MONTH_TO_CODE["C"][expiry.month]     # H for August
    body = (f"{root.upper()}{body_code}{expiry:%d}{expiry:%y}"
            f"{int(round(strike * 100)):05d}.U")
    return (f"{body}^{body_code}{expiry:%y}",        # as documented
            f"{body}^{call_code}{expiry:%y}")        # as LSEG keys it


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="UUUU")
    ap.add_argument("--field", default="MID_PRICE")
    ap.add_argument("--start", default="2026-06-15")
    ap.add_argument("--end", default="2026-08-28")
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    import lseg.data as ld
    ld.open_session()

    rows = []
    print(f"{'expiry':<12}{'K':>7}  {'documented ^put':>16}{'actual ^call':>15}")
    for expiry, strike in PAIRS:
        doc_ric, act_ric = put_rics(args.root, expiry, strike)
        counts = {}
        for label, ric in (("doc", doc_ric), ("act", act_ric)):
            try:
                d = ld.get_history(universe=[ric], fields=[args.field],
                                   start=args.start, end=args.end, interval="daily")
                counts[label] = 0 if d is None or d.empty else int(d.notna().sum().sum())
            except Exception:
                counts[label] = 0
        print(f"{str(expiry):<12}{strike:>7.2f}  {counts['doc']:>16}{counts['act']:>15}")
        rows.append({"expiry": str(expiry), "strike": strike,
                     "doc_ric": doc_ric, "doc": counts["doc"],
                     "act_ric": act_ric, "act": counts["act"]})
    ld.close_session()

    if args.write:
        OUT.write_text(json.dumps({
            "_comment": "Generated by scripts/probe_ric_suffix.py.",
            "probed_at": dt.date.today().isoformat(), "field": args.field,
            "window": [args.start, args.end], "rows": rows,
        }, indent=2) + "\n", encoding="utf-8")
        print(f"\nwrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
